### ISSUE TITLE
Three glitches: icon, logo, image via markdown

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Massively#6] opened 2019-01-10 20:56 UTC
Hello!

### A) icon

![a](https://user-images.githubusercontent.com/6694151/50996492-0465d580-14f0-11e9-81a7-f3975cc39871.jpg)

The down-arrow is not loading

### B) logo

![b](https://user-images.githubusercontent.com/6694151/50996510-134c8800-14f0-11e9-8a3b-a524a368ec4d.jpg)

Here the logo should load instead of the down-arrow.

### C) image via markdown

![c](https://user-images.githubusercontent.com/6694151/50996572-43942680-14f0-11e9-8709-199dea42e596.jpg)

Inserting an image via Koenig is good. But when I insert them via Markdown, they are not responsive.

## Details about my setup

* Ghost Version: 2.9.1
* CLI version: 1.9.4
* Node Version: 10.14.1
* Browser: Chrome 71
* OS X: 10.13.6
* Server: Docker [using this image](https://travis-ci.org/firepress-org/ghostfire/jobs/428717032)
* Database: SQLite

**Comment by AileenCGN** [comment] 2019-03-13 07:24
Hey @pascalandy 

I'm not able to reproduce the issue for the icon and the logo locally or on a server. How did you install the theme?  Can you check if any errors appear, or an ad-blocker is interfering with fetching things? 🤔 

I just pushed a fix for Markdown images:

![image](https://user-images.githubusercontent.com/8037602/54260430-d6f6e000-45a3-11e9-8aa4-dcf7f94bf121.png)

**Comment by AileenCGN** [comment] 2019-04-15 07:18
@pascalandy Are you still facing this issue?

**Comment by pascalandy** [comment] 2019-04-15 11:31
Hi,
It works but I see this.

![Screen Shot 2019-04-15 at 7 29 19 AM](https://user-images.githubusercontent.com/6694151/56129548-69e2bb80-5f50-11e9-8c02-ae0207f87980.jpg)

There is no message regarding the 'errors'.

**Comment by AileenCGN** [comment] 2019-04-16 01:59
@pascalandy That's a known and already fixed bug in master for the next release 😬 

Glad everything works now, I'm gonna close this issue now.

**Closed by AileenCGN** 2019-04-16 01:59 UTC
Labels: question

**Comment by pascalandy** [comment] 2019-04-16 02:38
Cool :)
